app = "eric693-discord-bot"  #（全球唯一）
primary_region = "nrt"    # 東京，對台灣最近

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

# Bot 不需要 HTTP，設成 worker
[processes]
  app = "python bot.py"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1